import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import { execFile } from "node:child_process";
import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { lstatSync, realpathSync } from "node:fs";
import { access, readdir, readFile, stat } from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { DEFAULT_AGENT_ID, DEFAULT_VAULT_PATH, PLUGIN_ROOT, minniHome } from "./config.js";
import { buildStatusReport } from "./sovereign.js";
import { prepareOutcome, prepareTask, type PrepareOutcomeInput, type PrepareTaskInput } from "./task.js";
import { auditTail } from "./vault.js";
import { readRecallState } from "./recall-state.js";
import { routeMemoryIntent } from "./policy.js";

const MAX_JSON_BYTES = 256 * 1024;
const DEFAULT_UI_HOST = process.env.MINNI_UI_HOST ?? "127.0.0.1";
const DEFAULT_UI_PORT = Number(process.env.MINNI_UI_PORT ?? "8765");
const DEFAULT_DEEP_RESEARCH_ROOT = process.env.DEEP_RESEARCH_AGENT_ROOT ?? path.join(os.homedir(), "deep-research-agent");
const DEFAULT_DEEP_RESEARCH_CLI =
  process.env.DEEP_RESEARCH_CLI ?? path.join(DEFAULT_DEEP_RESEARCH_ROOT, ".venv", "bin", "deep-research");
const DEFAULT_DEEP_RESEARCH_PYTHON =
  process.env.DEEP_RESEARCH_PYTHON ?? path.join(DEFAULT_DEEP_RESEARCH_ROOT, ".venv", "bin", "python");
const configuredConsoleAuth = (process.env.MINNI_CONSOLE_TOKEN ?? "").trim();
// X4: the sensitive console routes (/api/status, /api/prepare-*, /api/candidates)
// must NEVER be reachable without a bearer token. When the operator has not set
// MINNI_CONSOLE_TOKEN we auto-generate one at startup (and print it, see main())
// rather than failing open on the tokenless default. `effectiveConsoleAuth` is
// what every auth check compares against.
const consoleAuthAutoGenerated = configuredConsoleAuth.length === 0;
const effectiveConsoleAuth = consoleAuthAutoGenerated
  ? randomBytes(32).toString("hex")
  : configuredConsoleAuth;
// Dev escape hatch: MINNI_CONSOLE_NO_AUTH=1 skips the bearer-token check.
// Only honored when the server is bound to a local host (see createUiServer);
// the Host/Origin locality guards in the request handler still apply.
const consoleAuthOptOut = process.env.MINNI_CONSOLE_NO_AUTH === "1";
const DEEP_RESEARCH_ENABLED = process.env.MINNI_CONSOLE_DEEP_RESEARCH === "1";
const execFileAsync = promisify(execFile);

type ResearchMode = "web" | "local-docs" | "hybrid";
type ResearchTool = "google_search" | "url_context" | "code_execution";

interface DeepResearchRunSummary {
  run_id: string;
  created_at?: string;
  updated_at?: string;
  prompt?: string;
  mode?: string;
  interaction_id?: string | null;
  status?: string;
  has_result?: boolean;
  has_report?: boolean;
  has_events?: boolean;
}

interface DeepResearchBridge {
  paths: () => Promise<unknown>;
  listRuns: () => Promise<unknown>;
  getRun: (runId: string) => Promise<unknown>;
  localDocsManifest: () => Promise<unknown>;
  listFileStores: () => Promise<unknown>;
  createFileStore: (displayName?: string) => Promise<unknown>;
  deleteFileStore: (name: string) => Promise<unknown>;
  plan: (body: Record<string, unknown>) => Promise<unknown>;
  refinePlan: (body: Record<string, unknown>) => Promise<unknown>;
  approvePlan: (body: Record<string, unknown>) => Promise<unknown>;
  run: (body: Record<string, unknown>) => Promise<unknown>;
  status: (body: Record<string, unknown>) => Promise<unknown>;
}

export interface UiServerOptions {
  host?: string;
  port?: number;
  staticRoot?: string;
  vaultPath?: string;
  /** Override MINNI_HOME for vault catalogue scans (tests). */
  minniHomePath?: string;
  prepareTask?: (input: PrepareTaskInput) => Promise<unknown>;
  prepareOutcome?: (input: PrepareOutcomeInput) => Promise<unknown>;
  status?: () => Promise<unknown>;
  auditTail?: (limit: number) => Promise<unknown>;
  deepResearch?: DeepResearchBridge;
  /** Test seam: override daemon JSON-RPC for candidates/resolve without a live socket. */
  daemonRpc?: (method: string, params: Record<string, unknown>) => Promise<unknown>;
  /** Test seam: override recall-state reader. */
  readRecallState?: (vaultPath: string) => Promise<unknown>;
  /** Test seam: override agents catalogue builder. */
  listAgents?: () => Promise<unknown>;
  /** Test seam: override policy report builder. */
  policyReport?: () => Promise<unknown>;
}

export interface UiServerHandle {
  host: string;
  port: number;
  server: Server;
  start: () => Promise<void>;
  close: () => Promise<void>;
}

function sendJson(res: ServerResponse, statusCode: number, body: unknown): void {
  const payload = JSON.stringify(body, null, 2);
  res.writeHead(statusCode, {
    "Content-Type": "application/json; charset=utf-8",
    "Content-Length": Buffer.byteLength(payload),
    "Cache-Control": "no-store",
  });
  res.end(payload);
}

function sendText(res: ServerResponse, statusCode: number, body: string): void {
  res.writeHead(statusCode, {
    "Content-Type": "text/plain; charset=utf-8",
    "Content-Length": Buffer.byteLength(body),
    "Cache-Control": "no-store",
  });
  res.end(body);
}

function localHostAllowed(hostHeader: string | undefined): boolean {
  if (!hostHeader) return true;
  const host = hostHeader.startsWith("[")
    ? hostHeader.slice(1, hostHeader.indexOf("]"))
    : hostHeader.split(":")[0].toLowerCase();
  return host === "127.0.0.1" || host === "localhost" || host === "::1";
}

function localBindHostAllowed(host: string): boolean {
  return host === "127.0.0.1" || host === "localhost" || host === "::1";
}

function localOriginAllowed(origin: string | undefined): boolean {
  if (!origin) return true;
  try {
    return localBindHostAllowed(new URL(origin).hostname);
  } catch {
    return false;
  }
}

function fetchSiteAllowed(value: string | undefined): boolean {
  return !value || value === "same-origin" || value === "same-site" || value === "none";
}

// Constant-time string comparison (PR91-7). timingSafeEqual requires equal-length
// buffers, so we first hash both inputs to fixed-length SHA-256 digests and
// compare those: the comparison is constant-time AND leaks nothing about the
// token's length (an early length-mismatch return would have been a timing
// oracle on length). Equal strings -> equal digests -> true.
function safeStrEqual(a: string, b: string): boolean {
  const ah = createHash("sha256").update(a, "utf8").digest();
  const bh = createHash("sha256").update(b, "utf8").digest();
  return timingSafeEqual(ah, bh);
}

function consoleAuthRequired(pathname: string): boolean {
  // /api/health is the only unauthenticated API route (liveness probe, no vault data).
  if (pathname === "/api/health") return false;
  // X4: every vault-derived route requires a bearer token UNCONDITIONALLY — no
  // longer gated on MINNI_CONSOLE_TOKEN being set. When the operator has not set
  // a token, effectiveConsoleAuth is an auto-generated secret (printed on
  // startup), so the tokenless default is closed instead of open. This covers
  // /api/status, /api/prepare-*, /api/candidates, /api/audit-tail, and
  // /api/deep-research alike.
  if (pathname.startsWith("/api/")) return true;
  // The static shell (index.html, app.js, styles.css) carries no vault data and
  // must load without auth so a browser can reach the in-app token gate at all;
  // serveStatic confines reads to staticRoot. Every /api route above still
  // rejects tokenless requests, so the data plane stays closed.
  return false;
}

function consoleAuthorized(req: IncomingMessage, pathname: string, authDisabled: boolean): boolean {
  if (authDisabled) return true;
  if (!consoleAuthRequired(pathname)) return true;
  if (!effectiveConsoleAuth) return false;
  const auth = req.headers.authorization ?? "";
  return safeStrEqual(auth, `Bearer ${effectiveConsoleAuth}`);
}

function jsonContentTypeAllowed(value: string | undefined): boolean {
  return value?.toLowerCase().split(";")[0].trim() === "application/json";
}

function parseAuditLimit(value: string | null): number {
  const parsed = Number(value ?? 20);
  if (!Number.isFinite(parsed)) return 20;
  return Math.max(1, Math.min(Math.trunc(parsed), 100));
}

function parseCandidatesLimit(value: string | null): number {
  const parsed = Number(value ?? 50);
  if (!Number.isFinite(parsed)) return 50;
  return Math.max(1, Math.min(Math.trunc(parsed), 200));
}

// Daemon agent ids are lowercase slugs; anything else is rejected rather than
// forwarded as a principal claim.
const AGENT_ID_RE = /^[a-z0-9][a-z0-9._-]{0,63}$/;

// The env fallback sentinel resolves to a default-deny principal daemon-side,
// which would render the staged wall permanently (and silently) empty.
function candidatesAgentId(param: string | null): string | undefined {
  if (param && AGENT_ID_RE.test(param)) return param;
  return DEFAULT_AGENT_ID === "unknown-agent" ? undefined : DEFAULT_AGENT_ID;
}

/**
 * Console identity stamp for /api/status — who list_candidates / resolve will claim.
 * Capabilities are intentionally omitted: the bridge does not load principals/*.json
 * and must not invent a hardcoded grant list. Caps are daemon-side only.
 */
export function consolePrincipalReport(): {
  agentId: string;
  stampedForCandidates: string | null;
  unknownAgent: boolean;
  resolveOperatorsEnv: boolean;
} {
  const stamped = candidatesAgentId(null) ?? null;
  return {
    agentId: DEFAULT_AGENT_ID,
    stampedForCandidates: stamped,
    unknownAgent: DEFAULT_AGENT_ID === "unknown-agent",
    resolveOperatorsEnv: Boolean((process.env.MINNI_RESOLVE_OPERATORS ?? "").trim()),
  };
}

// ── agents catalogue helpers ────────────────────────────────────────────────

/** Map vault directory basename (e.g. claudecode-vault) → agent id. */
export function agentIdFromVaultDir(dirName: string): string {
  const base = dirName.replace(/-vault$/i, "");
  if (base === "claudecode" || base === "claude") return "claude-code";
  return base;
}

function homeDisplayPath(absPath: string): string {
  const home = os.homedir();
  if (absPath === home || absPath.startsWith(home + path.sep)) {
    return "~" + absPath.slice(home.length);
  }
  // Also rewrite MINNI_HOME-relative paths when home is overridden in tests.
  return absPath;
}

/**
 * Read-only audit tail for catalogue last-seen. Never calls ensureVault
 * (which would materialize vault skeletons / follow symlinks for write).
 */
export async function readOnlyAuditTail(
  vaultPath: string,
  limit = 5,
): Promise<{ entries: string[]; text: string }> {
  const today = new Date().toISOString().slice(0, 10);
  const todayPath = path.join(vaultPath, "logs", `${today}.md`);
  const fallbackPath = path.join(vaultPath, "log.md");
  let text = "";
  try {
    text = await readFile(todayPath, "utf8");
  } catch {
    try {
      text = await readFile(fallbackPath, "utf8");
    } catch {
      return { entries: [], text: "" };
    }
  }
  const entries = text
    .split(/^## /m)
    .filter((entry) => entry.trim().length > 0 && !entry.startsWith("#"))
    .map((entry) => `## ${entry.trim()}`)
    .slice(-limit);
  return { entries, text: entries.join("\n\n") };
}

/** True when vaultAbs is a real directory under realpath(homePath), not a symlink escape. */
export function vaultPathContained(vaultAbs: string, homePath: string): boolean {
  try {
    const st = lstatSync(vaultAbs);
    if (st.isSymbolicLink()) return false;
    if (!st.isDirectory()) return false;
    const realHome = realpathSync(homePath);
    const realVault = realpathSync(vaultAbs);
    return realVault === realHome || realVault.startsWith(realHome + path.sep);
  } catch {
    return false;
  }
}

function capsFromCapabilityList(caps: unknown): { R: 0 | 1; L: 0 | 1; H: 0 | 1 } {
  if (!Array.isArray(caps)) return { R: 0, L: 0, H: 0 };
  const set = new Set(caps.map((c) => String(c).toLowerCase()));
  if (set.has("*")) return { R: 1, L: 1, H: 1 };
  const r = set.has("search") || set.has("read") || set.has("recall") ? 1 : 0;
  const l = set.has("learn") || set.has("write") ? 1 : 0;
  const h = set.has("handoff") || set.has("cross_agent") || set.has("govern") ? 1 : 0;
  return { R: r as 0 | 1, L: l as 0 | 1, H: h as 0 | 1 };
}

/** Load R/L/H caps from principals/*.json (+ platform_agent_capabilities). */
export async function loadAgentCapsMap(homePath: string): Promise<Map<string, { R: 0 | 1; L: 0 | 1; H: 0 | 1 }>> {
  const out = new Map<string, { R: 0 | 1; L: 0 | 1; H: 0 | 1 }>();
  const principalsDir = path.join(homePath, "principals");
  let files: string[] = [];
  try {
    files = await readdir(principalsDir);
  } catch {
    return out;
  }
  for (const file of files) {
    if (!file.endsWith(".json") || file.includes(".bak")) continue;
    try {
      const raw = JSON.parse(await readFile(path.join(principalsDir, file), "utf8")) as Record<string, unknown>;
      const agentId = typeof raw.agent_id === "string" ? raw.agent_id : file.replace(/\.json$/, "");
      out.set(agentId, capsFromCapabilityList(raw.capabilities));
      const platform = raw.platform_agent_capabilities;
      if (platform && typeof platform === "object" && !Array.isArray(platform)) {
        for (const [pid, pcaps] of Object.entries(platform as Record<string, unknown>)) {
          out.set(pid, capsFromCapabilityList(pcaps));
        }
      }
    } catch {
      // skip malformed principal files
    }
  }
  return out;
}

function parseAuditTimestampMs(entry: string): number | null {
  const first = entry.split(/\r?\n/, 1)[0] || entry;
  const m = /^##\s+\[([^\]]+)\]/.exec(first);
  if (!m) return null;
  const ts = m[1].trim();
  // ISO-ish first
  const iso = Date.parse(ts.includes("T") ? ts : ts.replace(" ", "T"));
  if (Number.isFinite(iso)) return iso;
  return null;
}

function humanizeSeen(ms: number | null, now = Date.now()): string {
  if (ms == null || !Number.isFinite(ms)) return "—";
  const diffMs = now - ms;
  if (diffMs < 0) return "—";
  const mins = Math.floor(diffMs / 60000);
  if (mins < 60) return `${Math.max(1, mins)}m`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h`;
  const days = Math.floor(hours / 24);
  return `${days}d`;
}

/**
 * Compose the multi-agent vault catalogue for RUNTIMES / VaultsScreen.
 * Scans MINNI_HOME/*-vault, last-seen via read-only audit tail (never ensureVault),
 * staged count via list_candidates(status=proposed) per agent, caps from principals.
 *
 * Fail-loud staged counts: RPC failure → staged: null + stagedUnknown: true (not 0).
 * Symlink / path-escape vault entries are skipped.
 */
export async function buildAgentsCatalogue(options: {
  homePath: string;
  daemonRpc: (method: string, params: Record<string, unknown>) => Promise<unknown>;
  auditTailFn?: (vaultPath: string, limit: number) => Promise<{ entries?: string[] }>;
}): Promise<{ agents: Array<Record<string, unknown>>; count: number }> {
  const homePath = options.homePath;
  const capsMap = await loadAgentCapsMap(homePath);
  const tailFn = options.auditTailFn ?? readOnlyAuditTail;

  let dirs: string[] = [];
  try {
    dirs = await readdir(homePath);
  } catch {
    return { agents: [], count: 0 };
  }

  const vaultDirs = dirs.filter((d) => d.endsWith("-vault"));
  const agents: Array<Record<string, unknown>> = [];
  const now = Date.now();

  for (const dir of vaultDirs.sort()) {
    const vaultAbs = path.join(homePath, dir);
    if (!vaultPathContained(vaultAbs, homePath)) continue;

    const id = agentIdFromVaultDir(dir);
    // Skip vault basenames that would not be valid daemon agent ids.
    if (!AGENT_ID_RE.test(id)) continue;

    let lastSeenMs: number | null = null;
    try {
      const tail = await tailFn(vaultAbs, 5);
      for (const entry of [...(tail.entries || [])].reverse()) {
        const ms = parseAuditTimestampMs(entry);
        if (ms != null) {
          lastSeenMs = ms;
          break;
        }
      }
    } catch {
      // audit unavailable — honest "—" for seen
    }

    let staged: number | null = null;
    let stagedUnknown = false;
    try {
      const rpc = await options.daemonRpc("list_candidates", {
        limit: 200,
        status: "proposed",
        agent_id: id,
      });
      const unwrapped = unwrapDaemonCandidates(rpc);
      staged = unwrapped.candidates.length;
    } catch {
      // Fail-loud: do not invent 0 when the RPC failed.
      staged = null;
      stagedUnknown = true;
    }

    const caps = capsMap.get(id) ?? { R: 0 as const, L: 0 as const, H: 0 as const };
    const seen = humanizeSeen(lastSeenMs, now);
    const on = lastSeenMs != null && now - lastSeenMs < 60 * 60 * 1000;

    agents.push({
      id,
      vault: homeDisplayPath(vaultAbs),
      // Display path only — no absolute vaultPath on the wire (path leak).
      seen,
      lastSeenAt: lastSeenMs,
      on,
      caps,
      staged,
      stagedUnknown,
    });
  }

  return { agents, count: agents.length };
}

/** Normalize list_candidates daemon responses (JsonResult or flat). */
export function unwrapDaemonCandidates(rpc: unknown): { candidates: unknown[]; principal?: string; count?: number } {
  const r = rpc as Record<string, unknown> | null;
  if (!r || typeof r !== "object") return { candidates: [] };
  if (typeof r.ok === "boolean") {
    if (!r.ok) {
      throw new Error(String(r.error || "list_candidates failed"));
    }
    const data = (r.data && typeof r.data === "object" ? r.data : r) as Record<string, unknown>;
    const candidates = Array.isArray(data.candidates) ? data.candidates : [];
    return {
      candidates,
      principal: typeof data.principal === "string" ? data.principal : undefined,
      count: typeof data.count === "number" ? data.count : candidates.length,
    };
  }
  if (r.error) throw new Error(String(r.error));
  const candidates = Array.isArray(r.candidates) ? r.candidates : [];
  return {
    candidates,
    principal: typeof r.principal === "string" ? r.principal : undefined,
    count: typeof r.count === "number" ? r.count : candidates.length,
  };
}

/** Build a real policy/caps snapshot for PolicyScreen (no hardcoded version strings). */
export async function buildPolicyReport(options: {
  homePath: string;
  vaultPath: string;
  status?: () => Promise<unknown>;
}): Promise<Record<string, unknown>> {
  const capsMap = await loadAgentCapsMap(options.homePath);
  const agentId = DEFAULT_AGENT_ID;
  const stamped = candidatesAgentId(null) ?? null;
  const myCaps = capsMap.get(agentId) ?? capsMap.get("main") ?? { R: 0, L: 0, H: 0 };

  // Intent routing sample — live policy.ts heuristic, not a version brand.
  const sampleIntent = routeMemoryIntent("what did we decide about handoffs?");

  let afm: Record<string, unknown> = {};
  let automaticLearning: boolean | undefined;
  try {
    const report = (options.status
      ? await options.status()
      : await buildStatusReport({ vaultPath: options.vaultPath })) as unknown as Record<
      string,
      unknown
    >;
    const afmField = report.afm;
    if (afmField && typeof afmField === "object") afm = afmField as Record<string, unknown>;
    // Prefer explicit status field when present; otherwise omit (do not invent false).
    if (typeof (report as { automaticLearning?: unknown }).automaticLearning === "boolean") {
      automaticLearning = (report as { automaticLearning: boolean }).automaticLearning;
    }
  } catch {
    afm = { ok: false, error: "status unavailable" };
  }

  return {
    agentId,
    stampedForCandidates: stamped,
    unknownAgent: agentId === "unknown-agent",
    resolveOperatorsEnv: Boolean((process.env.MINNI_RESOLVE_OPERATORS ?? "").trim()),
    caps: myCaps,
    principalsKnown: [...capsMap.keys()].sort(),
    ...(automaticLearning === undefined ? {} : { automaticLearning }),
    intentRouting: {
      sampleTask: "what did we decide about handoffs?",
      action: sampleIntent.action,
      confidence: sampleIntent.confidence,
      automaticAllowed: sampleIntent.automaticAllowed,
      reason: sampleIntent.reason,
    },
    afm,
    policyModule: "plugins/minni/src/policy.ts",
    source: "principals/*.json + routeMemoryIntent + /api/status AFM",
  };
}

/** Map daemon / JSON-RPC error text to an honest HTTP status for console routes. */
export function daemonRpcHttpStatus(err: unknown): number {
  const msg = err instanceof Error ? err.message : String(err);
  // Conflict: candidate already decided.
  if (/already_resolved/i.test(msg)) return 409;
  // AuthZ / identity / accept gates (not "daemon down").
  if (
    /unknown_identity|identity_mismatch|recovery_required|principal_mismatch|capability_denied|vault_root_denied|operator_only|accept_flagged_required/i.test(
      msg,
    )
  ) {
    return 403;
  }
  // Missing row — keep specific; do NOT match bare "not found" (catches "Method not found").
  if (/candidate_not_found|unknown candidate/i.test(msg)) return 404;
  // JSON-RPC validation / bad params (sovereign forwards error.message only — no numeric code).
  // Keep anchors tight so a generic "X must be Y" daemon exception does not look like a client 400.
  // Covers: candidate_id is required / must be integer / decision must be one of /
  // agent_id must be a non-empty string / invalid agent_id … (validate_agent_id).
  if (
    /Invalid params|is required|must be (one of|an? |integer|a string|a non-empty string)|invalid agent_id/i.test(
      msg,
    )
  ) {
    return 400;
  }
  // Unknown RPC method on an older daemon.
  if (/Method not found/i.test(msg)) return 501;
  return 502;
}

function contentTypeFor(filePath: string): string {
  if (filePath.endsWith(".html")) return "text/html; charset=utf-8";
  if (filePath.endsWith(".css")) return "text/css; charset=utf-8";
  if (filePath.endsWith(".js")) return "text/javascript; charset=utf-8";
  if (filePath.endsWith(".svg")) return "image/svg+xml";
  if (filePath.endsWith(".png")) return "image/png";
  return "application/octet-stream";
}

async function readJsonBody(req: IncomingMessage): Promise<Record<string, unknown>> {
  const chunks: Buffer[] = [];
  let total = 0;
  for await (const chunk of req) {
    const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
    total += buffer.length;
    if (total > MAX_JSON_BYTES) throw new Error("Request body too large.");
    chunks.push(buffer);
  }
  const raw = Buffer.concat(chunks).toString("utf8").trim();
  if (!raw) return {};
  const parsed = JSON.parse(raw) as unknown;
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("JSON body must be an object.");
  return parsed as Record<string, unknown>;
}

function stringArray(value: unknown): string[] | undefined {
  if (!Array.isArray(value)) return undefined;
  return value.filter((item): item is string => typeof item === "string");
}

function numberValue(value: unknown): number | undefined {
  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

function boolValue(value: unknown): boolean | undefined {
  return typeof value === "boolean" ? value : undefined;
}

function stringValue(value: unknown): string | undefined {
  return typeof value === "string" ? value : undefined;
}

function researchModeValue(value: unknown): ResearchMode {
  return value === "local-docs" || value === "hybrid" || value === "web" ? value : "web";
}

function researchToolArray(value: unknown): ResearchTool[] | undefined {
  const values = stringArray(value);
  if (!values) return undefined;
  return values.filter((item): item is ResearchTool =>
    item === "google_search" || item === "url_context" || item === "code_execution",
  );
}

function appendListArgs(args: string[], flag: string, values: string[] | undefined): void {
  for (const value of values ?? []) {
    if (value.trim()) args.push(flag, value);
  }
}

function redactLocalValue(value: unknown): unknown {
  if (typeof value === "string") {
    const home = os.homedir().replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    return value
      .replace(/\/Users\/[^\s"',)]+/g, "[local-path]")
      .replace(/\/home\/[^\s"',)]+/g, "[local-path]")
      .replace(/\/Volumes\/[^\s"',)]+/g, "[local-path]")
      .replace(new RegExp(home + "[^\\s\"',)]*", "g"), "[local-path]")
      .replace(/\/tmp\/sov(?:ereign|rd)\.sock\b/g, "[local-path]")
      .replace(/[^\s"',)]+\.fmadapter\b/g, "[local-path]");
  }
  if (Array.isArray(value)) return value.map(redactLocalValue);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, redactLocalValue(item)]));
  }
  return value;
}

function prepareTaskInput(body: Record<string, unknown>, vaultPath: string): PrepareTaskInput {
  const task = stringValue(body.task);
  if (!task?.trim()) throw new Error("prepare-task requires task.");
  return {
    task,
    profile: body.profile === "compact" || body.profile === "standard" || body.profile === "deep" ? body.profile : undefined,
    budgetTokens: numberValue(body.budgetTokens),
    useAfm: boolValue(body.useAfm),
    layer:
      body.layer === "identity" || body.layer === "episodic" || body.layer === "knowledge" || body.layer === "artifact"
        ? body.layer
        : undefined,
    limit: numberValue(body.limit),
    workspaceId: stringValue(body.workspaceId),
    agentId: stringValue(body.agentId),
    vaultPath,
    includeVault: boolValue(body.includeVault),
  };
}

function prepareOutcomeInput(body: Record<string, unknown>, vaultPath: string): PrepareOutcomeInput {
  const task = stringValue(body.task);
  const summary = stringValue(body.summary);
  if (!task?.trim()) throw new Error("prepare-outcome requires task.");
  if (!summary?.trim()) throw new Error("prepare-outcome requires summary.");
  return {
    task,
    summary,
    changedFiles: stringArray(body.changedFiles),
    verification: stringArray(body.verification),
    profile: body.profile === "compact" || body.profile === "standard" || body.profile === "deep" ? body.profile : undefined,
    useAfm: boolValue(body.useAfm),
    vaultPath,
  };
}

function stripAnsi(value: string): string {
  return value.replace(/\u001b\[[0-9;]*m/g, "");
}

function parseJsonOutput(stdout: string): unknown {
  const text = stripAnsi(stdout).trim();
  try {
    return JSON.parse(text);
  } catch {
    const firstObject = text.indexOf("{");
    const firstArray = text.indexOf("[");
    const starts = [firstObject, firstArray].filter((item) => item >= 0);
    const start = starts.length ? Math.min(...starts) : -1;
    const end = Math.max(text.lastIndexOf("}"), text.lastIndexOf("]"));
    if (start >= 0 && end > start) return JSON.parse(text.slice(start, end + 1));
    throw new Error("Deep Research command did not return JSON.");
  }
}

async function runDeepResearchCli(args: string[]): Promise<unknown> {
  const { stdout } = await execFileAsync(DEFAULT_DEEP_RESEARCH_CLI, args, {
    cwd: DEFAULT_DEEP_RESEARCH_ROOT,
    maxBuffer: 20 * 1024 * 1024,
    timeout: 10 * 60 * 1000,
  });
  return parseJsonOutput(stdout);
}

const PLAN_FOLLOWUP_SCRIPT = `
import json
import sys
from deep_research_agent.research import ResearchService

payload = json.loads(sys.argv[1])
service = ResearchService()
action = payload["action"]
if action == "refine":
    result = service.refine_plan(payload["prompt"], previous_interaction_id=payload["previous_interaction_id"])
elif action == "approve":
    result = service.approve_plan(payload["prompt"], previous_interaction_id=payload["previous_interaction_id"])
else:
    raise ValueError("Unknown action")

if hasattr(result, "model_dump"):
    result = result.model_dump()
elif hasattr(result, "__dict__"):
    result = {k: v for k, v in vars(result).items() if not k.startswith("_")}
print(json.dumps(result, default=str))
`;

async function runDeepResearchPlanFollowup(
  action: "refine" | "approve",
  previousInteractionId: string,
  prompt: string,
): Promise<unknown> {
  const { stdout } = await execFileAsync(
    DEFAULT_DEEP_RESEARCH_PYTHON,
    ["-c", PLAN_FOLLOWUP_SCRIPT, JSON.stringify({ action, previous_interaction_id: previousInteractionId, prompt })],
    {
      cwd: DEFAULT_DEEP_RESEARCH_ROOT,
      maxBuffer: 20 * 1024 * 1024,
      timeout: 10 * 60 * 1000,
    },
  );
  return parseJsonOutput(stdout);
}

function deepResearchArgs(command: "plan" | "run", body: Record<string, unknown>): string[] {
  const prompt = stringValue(body.prompt);
  if (!prompt?.trim()) throw new Error(`deep-research ${command} requires prompt.`);
  const args = [command, prompt, "--mode", researchModeValue(body.mode)];
  appendListArgs(args, "--file-store", stringArray(body.fileSearchStores));
  appendListArgs(args, "--tool", researchToolArray(body.enabledTools));
  appendListArgs(args, "--document-uri", stringArray(body.documentUris));
  appendListArgs(args, "--image-uri", stringArray(body.imageUris));
  appendListArgs(args, "--mcp-server-json", stringArray(body.mcpServers));
  if (boolValue(body.maxMode)) args.push("--max-mode");
  if (command === "run" && boolValue(body.visualization)) args.push("--visualization");
  return args;
}

function safeRunId(value: string): string {
  if (!/^[0-9TZa-f-]+$/i.test(value)) throw new Error("Invalid Deep Research run id.");
  return value;
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function listDeepResearchRuns(): Promise<DeepResearchRunSummary[]> {
  const runsRoot = path.join(DEFAULT_DEEP_RESEARCH_ROOT, "runs");
  const names = await readdir(runsRoot);
  const runs: DeepResearchRunSummary[] = [];
  for (const name of names) {
    if (name.startsWith(".")) continue;
    const runDir = path.join(runsRoot, name);
    const metadataPath = path.join(runDir, "metadata.json");
    try {
      const metadata = JSON.parse(await readFile(metadataPath, "utf8")) as DeepResearchRunSummary;
      runs.push({
        ...metadata,
        has_result: await fileExists(path.join(runDir, "result.json")),
        has_report: await fileExists(path.join(runDir, "report.md")),
        has_events: await fileExists(path.join(runDir, "events.jsonl")),
      });
    } catch {
      /* Ignore incomplete run folders. */
    }
  }
  return runs.sort((a, b) => String(b.created_at ?? b.run_id).localeCompare(String(a.created_at ?? a.run_id)));
}

async function getDeepResearchRun(runId: string): Promise<unknown> {
  const id = safeRunId(runId);
  const runDir = path.join(DEFAULT_DEEP_RESEARCH_ROOT, "runs", id);
  const metadata = JSON.parse(await readFile(path.join(runDir, "metadata.json"), "utf8")) as DeepResearchRunSummary;
  const resultPath = path.join(runDir, "result.json");
  const reportPath = path.join(runDir, "report.md");
  const eventsPath = path.join(runDir, "events.jsonl");
  return {
    metadata,
    result: (await fileExists(resultPath)) ? JSON.parse(await readFile(resultPath, "utf8")) : null,
    report: (await fileExists(reportPath)) ? await readFile(reportPath, "utf8") : "",
    events: (await fileExists(eventsPath)) ? (await readFile(eventsPath, "utf8")).trim().split("\n").filter(Boolean).slice(-100) : [],
  };
}

function createDeepResearchBridge(): DeepResearchBridge {
  return {
    paths: async () => ({
      root: DEFAULT_DEEP_RESEARCH_ROOT,
      cli: DEFAULT_DEEP_RESEARCH_CLI,
      local_docs: path.join(DEFAULT_DEEP_RESEARCH_ROOT, "local-docs"),
      runs: path.join(DEFAULT_DEEP_RESEARCH_ROOT, "runs"),
    }),
    listRuns: listDeepResearchRuns,
    getRun: getDeepResearchRun,
    localDocsManifest: () => runDeepResearchCli(["local-docs-manifest"]),
    listFileStores: () => runDeepResearchCli(["list-file-stores"]),
    createFileStore: (displayName = "codex-local-docs") =>
      runDeepResearchCli(["create-file-store", "--display-name", displayName]),
    deleteFileStore: (name: string) => runDeepResearchCli(["delete-file-store", name]),
    plan: (body) => runDeepResearchCli(deepResearchArgs("plan", body)),
    refinePlan: (body) => {
      const previousInteractionId = stringValue(body.previousInteractionId);
      const prompt = stringValue(body.prompt);
      if (!previousInteractionId?.trim()) throw new Error("refine-plan requires previousInteractionId.");
      if (!prompt?.trim()) throw new Error("refine-plan requires prompt.");
      return runDeepResearchPlanFollowup("refine", previousInteractionId, prompt);
    },
    approvePlan: (body) => {
      const previousInteractionId = stringValue(body.previousInteractionId);
      const prompt = stringValue(body.prompt) ?? "Approve this collaborative plan and start execution.";
      if (!previousInteractionId?.trim()) throw new Error("approve-plan requires previousInteractionId.");
      return runDeepResearchPlanFollowup("approve", previousInteractionId, prompt);
    },
    run: (body) => runDeepResearchCli(deepResearchArgs("run", body)),
    status: (body) => {
      const interactionId = stringValue(body.interactionId);
      if (!interactionId?.trim()) throw new Error("status requires interactionId.");
      const args = ["status", interactionId];
      const runId = stringValue(body.runId);
      if (runId?.trim()) args.push("--run-id", safeRunId(runId));
      return runDeepResearchCli(args);
    },
  };
}

async function serveStatic(
  staticRoot: string,
  reqPath: string,
  method: string | undefined,
  res: ServerResponse,
): Promise<void> {
  const relative = reqPath === "/" ? "index.html" : decodeURIComponent(reqPath.replace(/^\/+/, ""));
  const fullPath = path.resolve(staticRoot, relative);
  const root = path.resolve(staticRoot);
  if (fullPath !== root && !fullPath.startsWith(`${root}${path.sep}`)) {
    sendText(res, 403, "Forbidden");
    return;
  }
  try {
    const info = await stat(fullPath);
    const filePath = info.isDirectory() ? path.join(fullPath, "index.html") : fullPath;
    const fileInfo = info.isDirectory() ? await stat(filePath) : info;
    if (method === "HEAD") {
      res.writeHead(200, {
        "Content-Type": contentTypeFor(filePath),
        "Content-Length": fileInfo.size,
        "Cache-Control": "no-store",
      });
      res.end();
      return;
    }
    const body = await readFile(filePath);
    res.writeHead(200, {
      "Content-Type": contentTypeFor(filePath),
      "Content-Length": body.length,
      "Cache-Control": "no-store",
    });
    res.end(body);
  } catch {
    sendText(res, 404, "Not found");
  }
}

export function createUiServer(options: UiServerOptions = {}): UiServerHandle {
  const host = options.host ?? DEFAULT_UI_HOST;
  const port = options.port ?? DEFAULT_UI_PORT;
  if (!localBindHostAllowed(host)) {
    throw new Error(`Minni console requires a local bind host, got: ${host}`);
  }
  const staticRoot = options.staticRoot ?? path.join(PLUGIN_ROOT, "frontend");
  const vaultPath = options.vaultPath ?? DEFAULT_VAULT_PATH;
  const homePath = options.minniHomePath ?? minniHome();
  const status = options.status ?? (() => buildStatusReport({ vaultPath }));
  const tail = options.auditTail ?? ((limit: number) => auditTail(vaultPath, limit));
  const taskPrep = options.prepareTask ?? ((input: PrepareTaskInput) => prepareTask(input));
  const outcomePrep = options.prepareOutcome ?? ((input: PrepareOutcomeInput) => prepareOutcome(input));
  const deepResearch = options.deepResearch ?? createDeepResearchBridge();
  const daemonRpc =
    options.daemonRpc ??
    (async (method: string, params: Record<string, unknown>) => {
      const { jsonRpcSocketRequestWithFallback } = await import("./sovereign.js");
      return jsonRpcSocketRequestWithFallback(method, params);
    });
  const recallStateReader =
    options.readRecallState ?? ((vp: string) => readRecallState(vp));
  const listAgents =
    options.listAgents ??
    (() =>
      buildAgentsCatalogue({
        homePath,
        daemonRpc,
      }));
  const policyReport =
    options.policyReport ??
    (() =>
      buildPolicyReport({
        homePath,
        vaultPath,
        status,
      }));

  /** Shared list_candidates route body for proposed / log_only / do_not_store. */
  async function candidatesByStatus(
    res: ServerResponse,
    statusFilter: string | undefined,
    limit: number,
    agentId: string | undefined,
  ): Promise<void> {
    try {
      const rpc = await daemonRpc("list_candidates", {
        limit,
        status: statusFilter,
        ...(agentId ? { agent_id: agentId } : {}),
      });
      if (rpc && typeof rpc === "object" && (rpc as { ok?: boolean }).ok === false) {
        const err = String((rpc as { error?: string }).error || "list_candidates failed");
        sendJson(res, daemonRpcHttpStatus(err), {
          ok: false,
          error: err,
          candidates: [],
        });
        return;
      }
      sendJson(res, 200, redactLocalValue(rpc));
    } catch (e) {
      sendJson(res, daemonRpcHttpStatus(e), {
        ok: false,
        error: e instanceof Error ? e.message : String(e),
        candidates: [],
      });
    }
  }

  const server = createServer(async (req, res) => {
    try {
      if (!localHostAllowed(req.headers.host)) {
        sendText(res, 403, "Minni console only accepts local host requests.");
        return;
      }
      if (!localOriginAllowed(req.headers.origin) || !fetchSiteAllowed(req.headers["sec-fetch-site"])) {
        sendText(res, 403, "Minni console only accepts same-origin local requests.");
        return;
      }

      const url = new URL(req.url ?? "/", `http://${req.headers.host ?? `${host}:${port}`}`);
      // consoleAuthOptOut is safe to honor here: createUiServer already threw on
      // any non-local bind host, so a tokenless console is never network-reachable.
      if (!consoleAuthorized(req, url.pathname, consoleAuthOptOut)) {
        sendJson(res, 403, { error: "console_auth_required", hint: "Set MINNI_CONSOLE_TOKEN and send Authorization: Bearer <token>" });
        return;
      }
      if (url.pathname.startsWith("/api/deep-research") && !DEEP_RESEARCH_ENABLED) {
        sendJson(res, 403, { error: "deep_research_disabled", hint: "Set MINNI_CONSOLE_DEEP_RESEARCH=1 to enable" });
        return;
      }

      if (req.method === "GET" && url.pathname === "/api/health") {
        sendJson(res, 200, {
          ok: true,
          host,
          port,
          tools: [
            "minni_prepare_task",
            "minni_prepare_outcome",
            "minni_status",
            "minni_audit_tail",
            "minni_candidates",
            "minni_resolve_candidate",
            "minni_agents",
            "minni_log_only",
            "minni_quarantine",
            "minni_recall_state",
            "minni_handoffs",
            "minni_policy",
            "deep_research_plan",
            "deep_research_run",
            "deep_research_status",
            "deep_research_local_docs",
          ],
          automaticLearning: false,
        });
        return;
      }
      if (req.method === "GET" && url.pathname === "/api/status") {
        const report = (await status()) as Record<string, unknown>;
        sendJson(
          res,
          200,
          redactLocalValue({
            ...report,
            principal: consolePrincipalReport(),
          }),
        );
        return;
      }
      if (req.method === "GET" && url.pathname === "/api/audit-tail") {
        sendJson(res, 200, redactLocalValue(await tail(parseAuditLimit(url.searchParams.get("limit")))));
        return;
      }
      if (req.method === "POST" && url.pathname === "/api/prepare-task") {
        if (!jsonContentTypeAllowed(req.headers["content-type"])) {
          sendText(res, 415, "POST requests must use application/json.");
          return;
        }
        const body = await readJsonBody(req);
        sendJson(res, 200, redactLocalValue(await taskPrep(prepareTaskInput(body, vaultPath))));
        return;
      }
      if (req.method === "POST" && url.pathname === "/api/prepare-outcome") {
        if (!jsonContentTypeAllowed(req.headers["content-type"])) {
          sendText(res, 415, "POST requests must use application/json.");
          return;
        }
        const body = await readJsonBody(req);
        sendJson(res, 200, redactLocalValue(await outcomePrep(prepareOutcomeInput(body, vaultPath))));
        return;
      }
      // G17: Candidates console API (minimal wiring for P1 approval pipeline)
      if (req.method === "GET" && url.pathname === "/api/candidates") {
        const limit = parseCandidatesLimit(url.searchParams.get("limit"));
        const candStatus = url.searchParams.get("status") || undefined;
        const agentId = candidatesAgentId(url.searchParams.get("agent_id"));
        await candidatesByStatus(res, candStatus, limit, agentId);
        return;
      }
      if (req.method === "GET" && url.pathname === "/api/log-only") {
        const limit = parseCandidatesLimit(url.searchParams.get("limit"));
        const agentId = candidatesAgentId(url.searchParams.get("agent_id"));
        await candidatesByStatus(res, "log_only", limit, agentId);
        return;
      }
      if (req.method === "GET" && url.pathname === "/api/quarantine") {
        const limit = parseCandidatesLimit(url.searchParams.get("limit"));
        const agentId = candidatesAgentId(url.searchParams.get("agent_id"));
        await candidatesByStatus(res, "do_not_store", limit, agentId);
        return;
      }
      if (req.method === "GET" && url.pathname === "/api/recall-state") {
        try {
          const state = await recallStateReader(vaultPath);
          if (!state) {
            sendJson(res, 200, {
              present: false,
              state: null,
              message: "no recent recall",
              vaultPath: homeDisplayPath(vaultPath),
            });
            return;
          }
          sendJson(res, 200, redactLocalValue({
            present: true,
            state,
            message: null,
            vaultPath: homeDisplayPath(vaultPath),
          }));
        } catch (e) {
          sendJson(res, 502, {
            ok: false,
            error: e instanceof Error ? e.message : String(e),
            present: false,
            state: null,
          });
        }
        return;
      }
      if (req.method === "GET" && url.pathname === "/api/agents") {
        try {
          const catalogue = await listAgents();
          sendJson(res, 200, redactLocalValue(catalogue));
        } catch (e) {
          sendJson(res, daemonRpcHttpStatus(e), {
            ok: false,
            error: e instanceof Error ? e.message : String(e),
            agents: [],
            count: 0,
          });
        }
        return;
      }
      if (req.method === "GET" && url.pathname === "/api/handoffs") {
        try {
          const agentId = candidatesAgentId(url.searchParams.get("agent_id"));
          const rpc = await daemonRpc("minni_list_pending_handoffs", {
            ...(agentId ? { agent_id: agentId } : {}),
          });
          if (rpc && typeof rpc === "object" && (rpc as { ok?: boolean }).ok === false) {
            const err = String((rpc as { error?: string }).error || "minni_list_pending_handoffs failed");
            sendJson(res, daemonRpcHttpStatus(err), {
              ok: false,
              error: err,
              handoffs: [],
            });
            return;
          }
          // JsonResult envelope: { ok, data: { agent_id, handoffs } } or flat.
          const r = rpc as Record<string, unknown>;
          if (r && typeof r === "object" && r.ok === true && r.data && typeof r.data === "object") {
            sendJson(res, 200, redactLocalValue(r.data));
            return;
          }
          sendJson(res, 200, redactLocalValue(rpc));
        } catch (e) {
          sendJson(res, daemonRpcHttpStatus(e), {
            ok: false,
            error: e instanceof Error ? e.message : String(e),
            handoffs: [],
          });
        }
        return;
      }
      if (req.method === "GET" && url.pathname === "/api/policy") {
        try {
          sendJson(res, 200, redactLocalValue(await policyReport()));
        } catch (e) {
          sendJson(res, 502, {
            ok: false,
            error: e instanceof Error ? e.message : String(e),
          });
        }
        return;
      }
      if (req.method === "POST" && url.pathname === "/api/resolve-candidate") {
        if (!jsonContentTypeAllowed(req.headers["content-type"])) {
          sendText(res, 415, "POST requests must use application/json.");
          return;
        }
        const body = await readJsonBody(req);
        try {
          const resolveAgentId = candidatesAgentId(null);
          const rpc = await daemonRpc("resolve_candidate", {
            candidate_id: body.candidate_id,
            decision: body.decision,
            reason: body.reason || body.resolution_reason || "",
            ...(resolveAgentId ? { agent_id: resolveAgentId } : {}),
          });
          if (rpc && typeof rpc === "object" && (rpc as { ok?: boolean }).ok === false) {
            const err = String((rpc as { error?: string }).error || "resolve_candidate failed");
            sendJson(res, daemonRpcHttpStatus(err), {
              ok: false,
              status: "error",
              error: err,
            });
            return;
          }
          sendJson(res, 200, redactLocalValue(rpc));
        } catch (e) {
          sendJson(res, daemonRpcHttpStatus(e), {
            ok: false,
            status: "error",
            error: e instanceof Error ? e.message : String(e),
          });
        }
        return;
      }
      if (req.method === "GET" && url.pathname === "/api/deep-research/paths") {
        sendJson(res, 200, redactLocalValue(await deepResearch.paths()));
        return;
      }
      if (req.method === "GET" && url.pathname === "/api/deep-research/runs") {
        sendJson(res, 200, redactLocalValue(await deepResearch.listRuns()));
        return;
      }
      const deepRunMatch = url.pathname.match(/^\/api\/deep-research\/runs\/([^/]+)$/);
      if (req.method === "GET" && deepRunMatch) {
        sendJson(res, 200, redactLocalValue(await deepResearch.getRun(deepRunMatch[1])));
        return;
      }
      if (req.method === "GET" && url.pathname === "/api/deep-research/local-docs-manifest") {
        sendJson(res, 200, redactLocalValue(await deepResearch.localDocsManifest()));
        return;
      }
      if (req.method === "GET" && url.pathname === "/api/deep-research/file-stores") {
        sendJson(res, 200, redactLocalValue(await deepResearch.listFileStores()));
        return;
      }
      if (req.method === "POST" && url.pathname.startsWith("/api/deep-research/")) {
        if (!jsonContentTypeAllowed(req.headers["content-type"])) {
          sendText(res, 415, "POST requests must use application/json.");
          return;
        }
        const body = await readJsonBody(req);
        if (url.pathname === "/api/deep-research/create-file-store") {
          sendJson(res, 200, redactLocalValue(await deepResearch.createFileStore(stringValue(body.displayName))));
          return;
        }
        if (url.pathname === "/api/deep-research/delete-file-store") {
          const name = stringValue(body.name);
          if (!name?.trim()) throw new Error("delete-file-store requires name.");
          sendJson(res, 200, redactLocalValue(await deepResearch.deleteFileStore(name)));
          return;
        }
        if (url.pathname === "/api/deep-research/plan") {
          sendJson(res, 200, redactLocalValue(await deepResearch.plan(body)));
          return;
        }
        if (url.pathname === "/api/deep-research/refine-plan") {
          sendJson(res, 200, redactLocalValue(await deepResearch.refinePlan(body)));
          return;
        }
        if (url.pathname === "/api/deep-research/approve-plan") {
          sendJson(res, 200, redactLocalValue(await deepResearch.approvePlan(body)));
          return;
        }
        if (url.pathname === "/api/deep-research/run") {
          sendJson(res, 200, redactLocalValue(await deepResearch.run(body)));
          return;
        }
        if (url.pathname === "/api/deep-research/status") {
          sendJson(res, 200, redactLocalValue(await deepResearch.status(body)));
          return;
        }
      }
      if (url.pathname.startsWith("/api/")) {
        sendText(res, 404, "Unknown API route.");
        return;
      }
      if (req.method !== "GET" && req.method !== "HEAD") {
        sendText(res, 405, "Method not allowed.");
        return;
      }
      await serveStatic(staticRoot, url.pathname, req.method, res);
    } catch (error) {
      sendJson(res, 400, { error: error instanceof Error ? error.message : String(error) });
    }
  });

  return {
    host,
    port,
    server,
    start: () =>
      new Promise<void>((resolve, reject) => {
        server.once("error", reject);
        server.listen(port, host, () => {
          server.off("error", reject);
          resolve();
        });
      }),
    close: () =>
      new Promise<void>((resolve, reject) => {
        server.close((error) => (error ? reject(error) : resolve()));
      }),
  };
}

async function main(): Promise<void> {
  const app = createUiServer();
  await app.start();
  console.log(`Minni console: http://${app.host}:${app.port}/`);
  // X4: when no MINNI_CONSOLE_TOKEN was configured we generated one so the
  // console is not open by default. Print it (once, to the operator's terminal)
  // so they can authenticate; a set token is never echoed.
  if (consoleAuthOptOut) {
    console.log(
      "Minni console auth: DISABLED (MINNI_CONSOLE_NO_AUTH=1). Local-only bind still enforced.\n" +
        "  Unset MINNI_CONSOLE_NO_AUTH to restore the bearer-token requirement.",
    );
  } else if (consoleAuthAutoGenerated) {
    console.log(
      "Minni console auth: MINNI_CONSOLE_TOKEN was not set — generated a session token.\n" +
        `  Open in a browser: http://${app.host}:${app.port}/?token=${effectiveConsoleAuth}\n` +
        `  Or send this header with console requests: Authorization: Bearer ${effectiveConsoleAuth}\n` +
        "  Set MINNI_CONSOLE_TOKEN to pin a stable token across restarts.",
    );
  }
}

const entry = process.argv[1] ? path.resolve(process.argv[1]) : "";
if (entry === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
